---
server.http2.enabled: true
spring:
  main.banner-mode: "off"
  profiles:
    active: local

logging:
  level:
    org.springframework.web.servlet: INFO
    org.springframework.data.mongodb.core:
      ReactiveMongoTemplate: DEBUG
      MongoTemplate: DEBUG

app:
  appName: "spring-kotlin-mongodb"
---
